name: rss_atom_reader
description: A Flutter RSS and Atom feed reader application.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  webfeed_plus: any
  intl: any
  url_launcher: any
  cached_network_image: any

flutter:
  uses-material-design: true
  assets:
    - assets/default_image.png
